# Generated by Django 4.1.4 on 2022-12-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_employee_feedback_spam_delete_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['text'], 'verbose_name': 'отзывы'},
        ),
        migrations.AlterModelOptions(
            name='spam',
            options={'ordering': ['email'], 'verbose_name': 'обратная связь.'},
        ),
    ]
